njuics/java-2018f-homework

- 20180911/朱向荣-161220187/Main.java
> 161220187-朱向荣

- 20180911/冷嘉怿-161220061/Sort.java
> Sort an array

- 20180911/张明超-161220168/sort.java
> 161220168 张明超

- 20180911/吴琳丽-161220140/BubbleSort.java
> 161220140_吴琳丽

- 20180911/高精成-151220029/Main.java
> First homework

- 20180911/陈哲霏-161220022/BubbleSort.java
> 陈哲霏-161220022

- 20180911/徐安孜-161220149/Array.java
> 161220149-徐安孜

- 20180911/戚赟-161220097/hw1_sort.java
> 戚赟_161220097

- 20180911/温宗儒-161220133/Sort.java
> 161220133 温宗儒

- 20180911/金亦凡-161220055/QuickSort.java
> java homework

- 20180911/周宇航-161220182/MySort.java
> 周宇航-161220182-作业一

- 20180911/韩金昌-141220036/Array.java
- 20180911/韩金昌-141220036/Sort.java
new file:   "Array.java"
new file:   "Sort.java"
> homework20180911_jchan

- 20180911/任意-161220101/sort.java
Your branch is up to date with 'origin/master'.
new file:   sort.java
> 任意-161220101

- 20180911/周新宇-161220181/QuickSort.java
new file:   20180911/周新宇-161220181/QuickSort.java
> first assignment

- 20180911/魏煜昂-161220132/ArraySort.java
> hw_161220132

- 20180911/李祐德-161220073/Sort.java
> java-homework1-李祐德-161220073

- 20180911/马白家欣-161220090/Sort.java
i have changed the style of my JAVA code
> i have changed the style of my JAVA code

- 20180911/韩金昌-141220036/Array.java
- 20180911/韩金昌-141220036/Sort.java
changes about:
type[] array
usage of {}
space between if/for and ()
space for =+-*/<>
an empty line between two code blocks(different usage)
exchange positions of array.show() and array.sort()
modified:   "Array.java"
modified:   "Sort.java"
> Changes20180914

- 20180911/钱鑫-161220099/sort.java
Your branch is up to date with 'origin/master'.
new file:   sort.java
> 161220099 钱鑫

- 20180911/祁煊-151220081/sort.java
> first-homework

- 20180911/黄文轩-161190037/Sort.java
> homework1-Sort

- 20180918/吴昌容-161220134/CalabashBrother.java
- 20180918/吴昌容-161220134/HomeWork2.java
new file:   "\345\220\264\346\230\214\345\256\271-161220134/CalabashBrother.java"
new file:   "\345\220\264\346\230\214\345\256\271-161220134/HomeWork2.java"
>  Changes to be committed: The Java Homework 2 from 161220134

- 20180918/许翔-161220153/Calabash.java
- 20180918/许翔-161220153/CalabashBros.java
JAVA Homework2, Xu Xiang 161220153
> JAVA Homework2, Xu Xiang 161220153

- 20180918/徐安孜-161220149/CalabashSort.java
> 徐安孜-161220149

- 20180918/王明-161220124/CalabashBro.java
- 20180918/王明-161220124/Lineup.java
> 王明-161220124

- 20180918/周新宇-161220181/BlueBoy.java
- 20180918/周新宇-161220181/CalabashBrothers.java
- 20180918/周新宇-161220181/CyanBoy.java
- 20180918/周新宇-161220181/GreenBoy.java
- 20180918/周新宇-161220181/OrangeBoy.java
- 20180918/周新宇-161220181/PurpleBoy.java
- 20180918/周新宇-161220181/RedBoy.java
- 20180918/周新宇-161220181/Sort.java
- 20180918/周新宇-161220181/YellowBoy.java
new file:   20180918/周新宇-161220181/BlueBoy.java
new file:   20180918/周新宇-161220181/CalabashBrothers.java
new file:   20180918/周新宇-161220181/CyanBoy.java
new file:   20180918/周新宇-161220181/GreenBoy.java
new file:   20180918/周新宇-161220181/OrangeBoy.java
new file:   20180918/周新宇-161220181/PurpleBoy.java
new file:   20180918/周新宇-161220181/RedBoy.java
new file:   20180918/周新宇-161220181/Sort.java
new file:   20180918/周新宇-161220181/YellowBoy.java
>  Committer: 周新宇 <njuzxy@zhouxinyudeMacBook-Pro.local>

- 20180918/金亦凡-161220055/Huluwa.java
> java homework 2

- 20180918/宗子靖-161220189/WorkTwo.java
> SecondWork

- 20180918/祁煊-151220081/Huluwa.java
- 20180918/祁煊-151220081/HuluwaSort.java
- 20180918/祁煊-151220081/Main.java
实现了葫芦娃随机排列 冒泡排序 快排 排序时报告出两两交换的位置
> 0918 2nd-homework

- 20180918/魏煜昂-161220132/Huluwa.java
- 20180918/魏煜昂-161220132/HuluwaBrothers.java
- 20180918/魏煜昂-161220132/TestExamples.java
> 161220132_homework2

- 20180925/祁煊-151220081/Battle.java
- 20180925/祁煊-151220081/Creature.java
- 20180925/祁煊-151220081/Grandpa.java
- 20180925/祁煊-151220081/Huluwa.java
- 20180925/祁煊-151220081/Louluo.java
- 20180925/祁煊-151220081/Main.java
- 20180925/祁煊-151220081/README.md
- 20180925/祁煊-151220081/SheJing.java
- 20180925/祁煊-151220081/XieziJing.java
> java_3rd_homework

- 20180918/张一飞-161130131/README.md
- 20180918/张一飞-161130131/SortForCalabash.java
Complete the full homework ahd push it
> the HW2 for 161130131

- 20180925/周梓康-161220183/BattleField.java
- 20180925/周梓康-161220183/Camp.java
- 20180925/周梓康-161220183/Cell.java
- 20180925/周梓康-161220183/Coordinate.java
- 20180925/周梓康-161220183/Creature.java
- 20180925/周梓康-161220183/Formation.java
- 20180925/周梓康-161220183/README.md
- 20180925/周梓康-161220183/Test.java
> 对代码进行第三次重构

- 20180911/徐天羿-151180151/Sort.java
- 20180918/徐天羿-151180151/CalabashBrothers.java
- 20180918/徐天羿-151180151/CalabashBrothersSort.java
homework 0911 v1.0
homework 0918 v1.0
> version1.0

- 20180925/徐天羿-151180151/ArrowFormation.java
- 20180925/徐天羿-151180151/CalabashBrothers.java
- 20180925/徐天羿-151180151/CalabashColor.java
- 20180925/徐天羿-151180151/Cheer.java
- 20180925/徐天羿-151180151/CraneFormation.java
- 20180925/徐天羿-151180151/Creature.java
- 20180925/徐天羿-151180151/Field.java
- 20180925/徐天羿-151180151/Formation.java
- 20180925/徐天羿-151180151/Grandpa.java
- 20180925/徐天羿-151180151/Monsters.java
- 20180925/徐天羿-151180151/README.md
- 20180925/徐天羿-151180151/Scorpion.java
- 20180925/徐天羿-151180151/Snake.java
- 20180925/徐天羿-151180151/SnakeFormation.java
- 20180925/徐天羿-151180151/Sort.java
- 20180925/徐天羿-151180151/SquareFormation.java
之前版本的READNE疑似有问题，现已解决
更新了泛型、集合框架等
> Version2.0

- .gitmodules
modified:   .gitmodules
new file:   "Final Project/\344\273\273\346\204\217-161220101"
> finalproject

- .gitmodules
- 20180911/孙楚涛-161220112/sort.java
- 20180918/孙楚涛-161220112/sort2.java
- 20180925/孙楚涛-161220112/project3-2/src/project3/Creature.java
- 20180925/孙楚涛-161220112/project3-2/src/project3/Formation.java
- 20180925/孙楚涛-161220112/project3-2/src/project3/Main.java
- 20180925/孙楚涛-161220112/project3-2/src/project3/NormalCreature.java
- 20180925/孙楚涛-161220112/project3-2/src/project3/ObjPlace.java
- 20180925/孙楚涛-161220112/project3-2/src/project3/Space.java
- 20180925/孙楚涛-161220112/project3-2/src/project3/SpecialCreature.java
- 20180925/孙楚涛-161220112/project3-2/src/project3/SupportCreature.java
- 20180925/孙楚涛-161220112/project3/src/project3/Creature.java
- 20180925/孙楚涛-161220112/project3/src/project3/Formation.java
- 20180925/孙楚涛-161220112/project3/src/project3/Main.java
- 20180925/孙楚涛-161220112/project3/src/project3/NormalCreature.java
- 20180925/孙楚涛-161220112/project3/src/project3/ObjPlace.java
- 20180925/孙楚涛-161220112/project3/src/project3/Space.java
- 20180925/孙楚涛-161220112/project3/src/project3/SpecialCreature.java
- 20180925/孙楚涛-161220112/project3/src/project3/SupportCreature.java
> 孙楚涛-161220112

- .gitmodules
> 大作业。助教辛苦了，2019新年快乐
